language: ruby
rvm:
  - 2.1.7

branches:
  only:
    - master

install: gem install -v 1.10.6 bundler --no-rdoc --no-ri
script: bundle _1.10.6_ install


notifications:
  hipchat: 372e05a530741a261bec75377fb7c2@MovieApp