language: ruby
rvm:
  - 2.1.7
  - 2.0.0
env:
  - DB=sqlite  
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database nanoblog_test' -U postgres

branches:
  only:
    - master

notifications:
  hipchat: 372e05a530741a261bec75377fb7c2@nanoblog